server: 
  appName: im
  host: 127.0.0.1
  port: 8635

mysql:
  dsn: root:123456@tcp(localhost:3306)/im?charset=utf8mb4&parseTime=True&loc=Local
  logType: 1 # 0 控制台，1 文件
  logFile: ./logs/mysql.log
  slowSqlThreshold: 1 # 慢查询日志，单位s
  logLevel: info # silent/error/warn/info

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

log:
  level: debug
  filename: ./logs/im.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true